name: UCX-Py documentation build

on:
  push:
    branches: ["gha-docs-build"]

jobs:
  build:
    name: Build Sphinx documentation
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v2.3.4
        with:
          path: latest
      - name: Checkout gh-pages
        uses: actions/checkout@v2.3.4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Install libnuma
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libnuma-dev
      - name: Create docs environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ucx_dev
          environment-file: conda/environments/builddocs_py37.yml
          auto-activate-base: false
      - name: Build documentation
        run: |
          cd latest/docs
          make html
      - name: Commit changes to docs
        run: |
          COMMIT_SHA=$(echo "${COMMIT_SHA}" | cut -c 1-7)
          rm -rf gh-pages/*
          cp -r latest/docs/build/html/* gh-pages/
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
          git add --all
          git commit --allow-empty -m "Update docs from ${COMMIT_SHA}"
          git push
      # - name: Push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     branch: gh-pages
      #     directory: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}