name: UCX-Py documentation build

on:
  push:
    branches: ["branch-0.20"]

jobs:
  build:
    name: Build Sphinx documentation
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Install libnuma
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libnuma-dev
      - name: Create docs environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ucx_dev
          environment-file: conda/environments/builddocs_py37.yml
          auto-activate-base: false
      - name: Build documentation
        run: |
          conda activate ucx_dev
          cd docs
          make html
      - name: Commit changes to docs
        run: |
          git clone https://github.com/rapidsai/ucx-py.git --branch gh-pages --single-branch gh-pages
          cp -r docs/build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}